name: pre-commit-cancel-if-changed
description:
  run pre-commit and optionally commit back to the pull request, and optionally cancel this workflow run if the pre-commit hook changed any
  files
author: 'Makeshift'
branding:
  icon: 'activity'
  color: 'blue'
inputs:
  extra_args:
    description: options to pass to pre-commit run
    required: false
    default: '--all-files'
  token:
    description: github token to clone / push with
    required: false
  git_user_name:
    description: github user name to push with
    required: false
    default: 'pre-commit'
  git_user_email:
    description: github user email to push with
    required: false
    default: 'pre-commit@example.com'
  git_commit_message:
    description: github commit message to push with
    required: false
    default: 'pre-commit fixes'
  cancel_if_changed:
    description: cancel this workflow run if the pre-commit hook changed any files
    required: false
    default: 'true'
  start_if_changed:
    description: start a new workflow run if the pre-commit hook changed any files
    required: false
    default: 'true'

runs:
  using: 'node16'
  main: 'dist/index.js'
